"""Constants for Casa ES Energy Manager."""

DOMAIN = "casa_es_energy_manager"
NAME = "Casa ES Energy Manager"
VERSION = "1.5.1"

# Core electrical sensors.
CONF_PV_POWER_SENSOR = "pv_power_sensor"
CONF_LOAD_POWER_SENSOR = "load_power_sensor"
CONF_GRID_POWER_SENSOR = "grid_power_sensor"
CONF_BATTERY_SOC_SENSOR = "battery_soc_sensor"
CONF_BATTERY_POWER_SENSOR = "battery_power_sensor"
CONF_PHASE_L1_POWER_SENSOR = "phase_l1_power_sensor"
CONF_PHASE_L2_POWER_SENSOR = "phase_l2_power_sensor"
CONF_PHASE_L3_POWER_SENSOR = "phase_l3_power_sensor"

# Solar opportunity / forecast sensors.
CONF_PV_POTENTIAL_POWER_SENSOR = "pv_potential_power_sensor"
CONF_PV_FORECAST_REMAINING_TODAY_SENSOR = "pv_forecast_remaining_today_sensor"
CONF_PV_FORECAST_CURRENT_HOUR_SENSOR = "pv_forecast_current_hour_sensor"
CONF_PV_FORECAST_NEXT_HOUR_SENSOR = "pv_forecast_next_hour_sensor"
CONF_PV_FORECAST_TODAY_SENSOR = "pv_forecast_today_sensor"
CONF_PV_FORECAST_TOMORROW_SENSOR = "pv_forecast_tomorrow_sensor"

# Optional contextual data for the AI planner.
CONF_WEATHER_ENTITY = "weather_entity"
CONF_EXTRA_CONTEXT_SENSORS = "extra_context_sensors"

# Electrical limits.
CONF_INVERTER_POWER_LIMIT = "inverter_power_limit"
CONF_PHASE_POWER_LIMIT = "phase_power_limit"
CONF_GRID_POWER_LIMIT = "grid_power_limit"
CONF_SAFETY_MARGIN = "safety_margin"  # legacy fallback
CONF_INVERTER_SAFETY_MARGIN = "inverter_safety_margin"
CONF_PHASE_SAFETY_MARGIN = "phase_safety_margin"
CONF_GRID_SAFETY_MARGIN = "grid_safety_margin"

# AI / battery planner.
CONF_AI_ENABLED = "ai_enabled"
CONF_AI_TASK_ENTITY = "ai_task_entity"
CONF_AI_INTERVAL_MINUTES = "ai_interval_minutes"
CONF_BATTERY_CAPACITY_KWH = "battery_capacity_kwh"
CONF_BATTERY_TARGET_SOC = "battery_target_soc"
CONF_BATTERY_TARGET_HOUR = "battery_target_hour"
CONF_EXPECTED_BASE_LOAD_W = "expected_base_load_w"
CONF_BATTERY_CHARGE_EFFICIENCY_PCT = "battery_charge_efficiency_pct"
CONF_ENERGY_PREFERENCE = "energy_preference"
ENERGY_PREFERENCE_BATTERY = "battery_first"
ENERGY_PREFERENCE_BALANCED = "balanced"
ENERGY_PREFERENCE_LOADS = "loads_first"
ENERGY_PREFERENCES = (
    ENERGY_PREFERENCE_BATTERY,
    ENERGY_PREFERENCE_BALANCED,
    ENERGY_PREFERENCE_LOADS,
)

# Real appliance control. This is intentionally opt-in and defaults OFF after
# every installation/update unless the user explicitly enables it.
CONF_AUTOMATIC_REAL_LOAD_CONTROL = "automatic_real_load_control"
DEFAULT_AUTOMATIC_REAL_LOAD_CONTROL = False
REAL_CONTROL_COMMAND_COOLDOWN_SECONDS = 15

# Manual emergency grid-charge hooks. The integration calls user-configured HA
# scripts so inverter-specific service details remain explicit and safe.
CONF_EMERGENCY_CHARGE_START_SCRIPT = "emergency_charge_start_script"
CONF_EMERGENCY_CHARGE_STOP_SCRIPT = "emergency_charge_stop_script"
CONF_EMERGENCY_CHARGE_TARGET_SOC = "emergency_charge_target_soc"
CONF_EMERGENCY_CHARGE_POWER_W = "emergency_charge_power_w"
CONF_EMERGENCY_CHARGE_MAX_MINUTES = "emergency_charge_max_minutes"

# Managed flexible-load subentries.
SUBENTRY_TYPE_MANAGED_DEVICE = "managed_device"
CONF_DEVICE_NAME = "name"
CONF_DEVICE_ENTITY = "entity_id"
CONF_DEVICE_POWER_SENSOR = "power_sensor"
CONF_DEVICE_NOMINAL_POWER_W = "nominal_power_w"
CONF_DEVICE_PRIORITY = "priority"
CONF_DEVICE_PHASE = "phase"
CONF_DEVICE_EXPECTED_RUNTIME_MINUTES = "expected_runtime_minutes"
CONF_DEVICE_MIN_BATTERY_SOC = "min_battery_soc"
CONF_DEVICE_ALLOW_GRID = "allow_grid"
CONF_DEVICE_ENABLED = "enabled"
CONF_DEVICE_ADAPTIVE_POWER = "adaptive_power_profile"
CONF_DEVICE_MIN_ON_MINUTES = "min_on_minutes"
CONF_DEVICE_MIN_OFF_MINUTES = "min_off_minutes"

# v1.2 device type and climate/PDC mode profiling.
CONF_DEVICE_TYPE = "device_type"
CONF_DEVICE_MODE_CLIMATE_ENTITY = "mode_climate_entity"
DEVICE_TYPE_GENERIC = "generic"
DEVICE_TYPE_CLIMATE = "climate"
DEVICE_TYPES = (DEVICE_TYPE_GENERIC, DEVICE_TYPE_CLIMATE)
DEFAULT_DEVICE_TYPE = DEVICE_TYPE_GENERIC

# Runtime per-device modes exposed as select entities.
DEVICE_MODE_AUTO = "auto"
DEVICE_MODE_OVERRIDE = "override"
DEVICE_MODE_OFF = "off"
DEVICE_MODES = (DEVICE_MODE_AUTO, DEVICE_MODE_OVERRIDE, DEVICE_MODE_OFF)

# Useful managed-load constraints retained for the user's real load set.
CONF_DEVICE_MIN_DAILY_RUNTIME_MINUTES = "min_daily_runtime_minutes"
CONF_DEVICE_MAX_DAILY_RUNTIME_MINUTES = "max_daily_runtime_minutes"
CONF_DEVICE_MAX_DAILY_ACTIVATIONS = "max_daily_activations"
CONF_DEVICE_SCHEDULE_DEADLINE = "schedule_deadline"
CONF_DEVICE_START_AFTER = "start_after"
CONF_DEVICE_END_BEFORE = "end_before"
CONF_DEVICE_AVERAGING_WINDOW_SECONDS = "averaging_window_seconds"
CONF_DEVICE_BIG_CONSUMER = "big_consumer"
CONF_DEVICE_BATTERY_DISCHARGE_OVERRIDE_W = "battery_discharge_override_w"
CONF_DEVICE_ON_ONLY = "on_only"
CONF_DEVICE_PROTECT_PREEMPTION = "protect_preemption"
CONF_DEVICE_SWITCH_INTERVAL_SECONDS = "switch_interval_seconds"
CONF_DEVICE_MAX_GRID_POWER_W = "max_grid_power_w"

# Legacy v1.0 keys intentionally kept only so old subentries can be read and cleaned safely.
CONF_DEVICE_REQUIRES_ENTITY = "requires_entity"
CONF_DEVICE_DYNAMIC_CURRENT = "dynamic_current"
CONF_DEVICE_CURRENT_ENTITY = "current_entity"
CONF_DEVICE_MIN_CURRENT_A = "min_current_a"
CONF_DEVICE_MAX_CURRENT_A = "max_current_a"
CONF_DEVICE_EV_SOC_SENSOR = "ev_soc_sensor"
CONF_DEVICE_EV_CONNECTED_SENSOR = "ev_connected_sensor"
CONF_DEVICE_EV_TARGET_SOC = "ev_target_soc"
LEGACY_REMOVED_DEVICE_KEYS = (
    CONF_DEVICE_REQUIRES_ENTITY,
    CONF_DEVICE_DYNAMIC_CURRENT,
    CONF_DEVICE_CURRENT_ENTITY,
    CONF_DEVICE_MIN_CURRENT_A,
    CONF_DEVICE_MAX_CURRENT_A,
    CONF_DEVICE_EV_SOC_SENSOR,
    CONF_DEVICE_EV_CONNECTED_SENSOR,
    CONF_DEVICE_EV_TARGET_SOC,
)

# Monitored loads.
SUBENTRY_TYPE_MONITORED_LOAD = "monitored_load"
CONF_MONITORED_LOAD_NAME = "name"
CONF_MONITORED_LOAD_POWER_SENSOR = "power_sensor"
CONF_MONITORED_LOAD_PHASE = "phase"
CONF_MONITORED_LOAD_ENABLED = "enabled"
CONF_MONITORED_LOAD_EMERGENCY_ENABLED = "emergency_control_enabled"
CONF_MONITORED_LOAD_EMERGENCY_MODE = "emergency_control_mode"
CONF_MONITORED_LOAD_EMERGENCY_ENTITY = "emergency_entity"
CONF_MONITORED_LOAD_RESUME_ENTITY = "resume_entity"
MONITORED_EMERGENCY_MODE_SWITCH = "switch"
MONITORED_EMERGENCY_MODE_PAUSE_RESUME = "pause_resume"
MONITORED_EMERGENCY_MODE_STOP_ONLY = "stop_only"
MONITORED_EMERGENCY_MODES = (
    MONITORED_EMERGENCY_MODE_SWITCH,
    MONITORED_EMERGENCY_MODE_PAUSE_RESUME,
    MONITORED_EMERGENCY_MODE_STOP_ONLY,
)
MONITORED_EMERGENCY_ACTIVE_POWER_THRESHOLD_W = 20.0
MONITORED_EMERGENCY_RECOVERY_STABLE_SECONDS = 120
DEFAULT_MONITORED_LOAD_ENABLED = True
DEFAULT_MONITORED_LOAD_EMERGENCY_ENABLED = False

BATTERY_RECOVERY_MEASURED_PV_MIN_W = 100.0
BATTERY_RECOVERY_POTENTIAL_PV_MIN_W = 200.0
BATTERY_RECOVERY_FORECAST_REMAINING_MIN_KWH = 0.05

DEVICE_PRIORITY_MIN = 1
DEVICE_PRIORITY_MAX = 100
DEVICE_PHASES = ("l1", "l2", "l3", "three_phase")

DEFAULT_INVERTER_POWER_LIMIT = 10_000.0
DEFAULT_PHASE_POWER_LIMIT = 3_000.0
DEFAULT_GRID_POWER_LIMIT = 6_000.0
DEFAULT_SAFETY_MARGIN = 250.0
DEFAULT_INVERTER_SAFETY_MARGIN = 250.0
DEFAULT_PHASE_SAFETY_MARGIN = 150.0
DEFAULT_GRID_SAFETY_MARGIN = 300.0

DEFAULT_AI_ENABLED = False
DEFAULT_AI_INTERVAL_MINUTES = 30
DEFAULT_BATTERY_CAPACITY_KWH = 14.3
DEFAULT_BATTERY_TARGET_SOC = 100.0
DEFAULT_BATTERY_TARGET_HOUR = 17
DEFAULT_EXPECTED_BASE_LOAD_W = 500.0
DEFAULT_BATTERY_CHARGE_EFFICIENCY_PCT = 95.0
DEFAULT_ENERGY_PREFERENCE = ENERGY_PREFERENCE_BALANCED

DEFAULT_EMERGENCY_CHARGE_TARGET_SOC = 100.0
DEFAULT_EMERGENCY_CHARGE_POWER_W = 3000.0
DEFAULT_EMERGENCY_CHARGE_MAX_MINUTES = 240

DEFAULT_DEVICE_PRIORITY = 50
DEFAULT_DEVICE_EXPECTED_RUNTIME_MINUTES = None
DEFAULT_DEVICE_MIN_BATTERY_SOC = 40.0
DEFAULT_DEVICE_ALLOW_GRID = False
DEFAULT_DEVICE_ENABLED = True
DEFAULT_DEVICE_ADAPTIVE_POWER = True
DEFAULT_DEVICE_MIN_ON_MINUTES = 0
DEFAULT_DEVICE_MIN_OFF_MINUTES = 0
DEFAULT_DEVICE_MIN_DAILY_RUNTIME_MINUTES = 0
DEFAULT_DEVICE_MAX_DAILY_RUNTIME_MINUTES = 1440
DEFAULT_DEVICE_MAX_DAILY_ACTIVATIONS = 0
DEFAULT_DEVICE_AVERAGING_WINDOW_SECONDS = 0
DEFAULT_DEVICE_BIG_CONSUMER = False
DEFAULT_DEVICE_BATTERY_DISCHARGE_OVERRIDE_W = 0.0
DEFAULT_DEVICE_ON_ONLY = False
DEFAULT_DEVICE_PROTECT_PREEMPTION = False
DEFAULT_DEVICE_SWITCH_INTERVAL_SECONDS = 0
DEFAULT_DEVICE_MAX_GRID_POWER_W = 0.0

ADAPTIVE_ACTIVE_POWER_THRESHOLD_W = 20.0
ADAPTIVE_PROFILE_MIN_SAMPLES = 20
ADAPTIVE_SAVE_EVERY_OBSERVATIONS = 60
ADAPTIVE_ESTIMATE_MAX_MEAN_FACTOR = 1.40

CURTAILMENT_SOC_THRESHOLD = 98.0
CURTAILMENT_POTENTIAL_GAP_W = 400.0
CURTAILMENT_GRID_IMPORT_MAX_W = 150.0

UPDATE_INTERVAL_SECONDS = 5
