"""Constants for Casa ES Energy Manager."""

DOMAIN = "casa_es_energy_manager"
NAME = "Casa ES Energy Manager"
VERSION = "0.4.2"

# Core electrical sensors.
CONF_PV_POWER_SENSOR = "pv_power_sensor"
CONF_LOAD_POWER_SENSOR = "load_power_sensor"
CONF_GRID_POWER_SENSOR = "grid_power_sensor"
CONF_BATTERY_SOC_SENSOR = "battery_soc_sensor"
CONF_BATTERY_POWER_SENSOR = "battery_power_sensor"
CONF_PHASE_L1_POWER_SENSOR = "phase_l1_power_sensor"
CONF_PHASE_L2_POWER_SENSOR = "phase_l2_power_sensor"
CONF_PHASE_L3_POWER_SENSOR = "phase_l3_power_sensor"

# Solar opportunity / forecast sensors.
CONF_PV_POTENTIAL_POWER_SENSOR = "pv_potential_power_sensor"
CONF_PV_FORECAST_REMAINING_TODAY_SENSOR = "pv_forecast_remaining_today_sensor"
CONF_PV_FORECAST_CURRENT_HOUR_SENSOR = "pv_forecast_current_hour_sensor"
CONF_PV_FORECAST_NEXT_HOUR_SENSOR = "pv_forecast_next_hour_sensor"
CONF_PV_FORECAST_TODAY_SENSOR = "pv_forecast_today_sensor"
CONF_PV_FORECAST_TOMORROW_SENSOR = "pv_forecast_tomorrow_sensor"

# Optional contextual data for the AI planner.
CONF_WEATHER_ENTITY = "weather_entity"
CONF_EXTRA_CONTEXT_SENSORS = "extra_context_sensors"

CONF_INVERTER_POWER_LIMIT = "inverter_power_limit"
CONF_PHASE_POWER_LIMIT = "phase_power_limit"
CONF_GRID_POWER_LIMIT = "grid_power_limit"
CONF_SAFETY_MARGIN = "safety_margin"

CONF_AI_ENABLED = "ai_enabled"
CONF_AI_TASK_ENTITY = "ai_task_entity"
CONF_AI_INTERVAL_MINUTES = "ai_interval_minutes"
CONF_BATTERY_CAPACITY_KWH = "battery_capacity_kwh"
CONF_BATTERY_TARGET_SOC = "battery_target_soc"
CONF_BATTERY_TARGET_HOUR = "battery_target_hour"
CONF_EXPECTED_BASE_LOAD_W = "expected_base_load_w"
CONF_BATTERY_CHARGE_EFFICIENCY_PCT = "battery_charge_efficiency_pct"

# Managed flexible-load subentries (dry-run only).
SUBENTRY_TYPE_MANAGED_DEVICE = "managed_device"
CONF_DEVICE_NAME = "name"
CONF_DEVICE_ENTITY = "entity_id"
CONF_DEVICE_POWER_SENSOR = "power_sensor"
CONF_DEVICE_NOMINAL_POWER_W = "nominal_power_w"
CONF_DEVICE_PRIORITY = "priority"
CONF_DEVICE_PHASE = "phase"
CONF_DEVICE_EXPECTED_RUNTIME_MINUTES = "expected_runtime_minutes"
CONF_DEVICE_MIN_BATTERY_SOC = "min_battery_soc"
CONF_DEVICE_ALLOW_GRID = "allow_grid"
CONF_DEVICE_ENABLED = "enabled"

# Options retained from the original PV Excess appliance model.
CONF_DEVICE_MIN_DAILY_RUNTIME_MINUTES = "min_daily_runtime_minutes"
CONF_DEVICE_MAX_DAILY_RUNTIME_MINUTES = "max_daily_runtime_minutes"
CONF_DEVICE_MAX_DAILY_ACTIVATIONS = "max_daily_activations"
CONF_DEVICE_SCHEDULE_DEADLINE = "schedule_deadline"
CONF_DEVICE_START_AFTER = "start_after"
CONF_DEVICE_END_BEFORE = "end_before"
CONF_DEVICE_REQUIRES_ENTITY = "requires_entity"
CONF_DEVICE_AVERAGING_WINDOW_SECONDS = "averaging_window_seconds"
CONF_DEVICE_BIG_CONSUMER = "big_consumer"
CONF_DEVICE_BATTERY_DISCHARGE_OVERRIDE_W = "battery_discharge_override_w"
CONF_DEVICE_ON_ONLY = "on_only"
CONF_DEVICE_PROTECT_PREEMPTION = "protect_preemption"
CONF_DEVICE_SWITCH_INTERVAL_SECONDS = "switch_interval_seconds"
CONF_DEVICE_MAX_GRID_POWER_W = "max_grid_power_w"
CONF_DEVICE_DYNAMIC_CURRENT = "dynamic_current"
CONF_DEVICE_CURRENT_ENTITY = "current_entity"
CONF_DEVICE_MIN_CURRENT_A = "min_current_a"
CONF_DEVICE_MAX_CURRENT_A = "max_current_a"
CONF_DEVICE_EV_SOC_SENSOR = "ev_soc_sensor"
CONF_DEVICE_EV_CONNECTED_SENSOR = "ev_connected_sensor"
CONF_DEVICE_EV_TARGET_SOC = "ev_target_soc"

# Numeric priority: 1 = highest, 10 = lowest.
DEVICE_PRIORITY_MIN = 1
DEVICE_PRIORITY_MAX = 10
DEVICE_PHASES = ("l1", "l2", "l3", "three_phase")

DEFAULT_INVERTER_POWER_LIMIT = 10_000.0
DEFAULT_PHASE_POWER_LIMIT = 3_000.0
DEFAULT_GRID_POWER_LIMIT = 6_000.0
DEFAULT_SAFETY_MARGIN = 250.0

DEFAULT_AI_ENABLED = False
DEFAULT_AI_INTERVAL_MINUTES = 30
DEFAULT_BATTERY_CAPACITY_KWH = 14.3
DEFAULT_BATTERY_TARGET_SOC = 100.0
DEFAULT_BATTERY_TARGET_HOUR = 17
DEFAULT_EXPECTED_BASE_LOAD_W = 500.0
DEFAULT_BATTERY_CHARGE_EFFICIENCY_PCT = 95.0

DEFAULT_DEVICE_PRIORITY = 5
DEFAULT_DEVICE_EXPECTED_RUNTIME_MINUTES = 60
DEFAULT_DEVICE_MIN_BATTERY_SOC = 40.0
DEFAULT_DEVICE_ALLOW_GRID = False
DEFAULT_DEVICE_ENABLED = True
DEFAULT_DEVICE_MIN_DAILY_RUNTIME_MINUTES = 0
DEFAULT_DEVICE_MAX_DAILY_RUNTIME_MINUTES = 1440
DEFAULT_DEVICE_MAX_DAILY_ACTIVATIONS = 0
DEFAULT_DEVICE_AVERAGING_WINDOW_SECONDS = 0
DEFAULT_DEVICE_BIG_CONSUMER = False
DEFAULT_DEVICE_BATTERY_DISCHARGE_OVERRIDE_W = 0.0
DEFAULT_DEVICE_ON_ONLY = False
DEFAULT_DEVICE_PROTECT_PREEMPTION = False
DEFAULT_DEVICE_SWITCH_INTERVAL_SECONDS = 300
DEFAULT_DEVICE_MAX_GRID_POWER_W = 0.0
DEFAULT_DEVICE_DYNAMIC_CURRENT = False
DEFAULT_DEVICE_MIN_CURRENT_A = 6.0
DEFAULT_DEVICE_MAX_CURRENT_A = 16.0
DEFAULT_DEVICE_EV_TARGET_SOC = 80.0

# Read-only heuristic used only to flag a likely zero-export curtailment condition.
CURTAILMENT_SOC_THRESHOLD = 98.0
CURTAILMENT_POTENTIAL_GAP_W = 400.0
CURTAILMENT_GRID_IMPORT_MAX_W = 150.0

UPDATE_INTERVAL_SECONDS = 5
